# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\'\n\x11\x45xperimentDetails\x12\x12\n\nproject_id\x18\x01 \x01(\t\".\n\x04\x44\x61ta\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x15\n\rdata_elements\x18\x02 \x03(\t2U\n\x0c\x64\x61taProvider\x12\x45\n\x10serverConnection\x12\x1d.helloworld.ExperimentDetails\x1a\x10.helloworld.Data\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_EXPERIMENTDETAILS']._serialized_start=32
  _globals['_EXPERIMENTDETAILS']._serialized_end=71
  _globals['_DATA']._serialized_start=73
  _globals['_DATA']._serialized_end=119
  _globals['_DATAPROVIDER']._serialized_start=121
  _globals['_DATAPROVIDER']._serialized_end=206
# @@protoc_insertion_point(module_scope)
